
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 24 16:31:01 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LOGEQ = 15;
  public static final int LBRACKET = 11;
  public static final int CONST = 41;
  public static final int CHAR = 5;
  public static final int LPAREN = 26;
  public static final int SEMI = 31;
  public static final int CONTINUE = 7;
  public static final int INT = 3;
  public static final int MINUS = 21;
  public static final int RPAREN = 27;
  public static final int AND = 30;
  public static final int LT = 18;
  public static final int OR = 29;
  public static final int BOOL = 4;
  public static final int COMMA = 9;
  public static final int CLASS = 42;
  public static final int INC = 32;
  public static final int DIV = 24;
  public static final int GEQ = 17;
  public static final int PLUS = 20;
  public static final int ASSIGN = 47;
  public static final int IF = 36;
  public static final int DOT = 12;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 13;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int MUL = 22;
  public static final int MOD = 23;
  public static final int NEQ = 14;
  public static final int BREAK = 6;
  public static final int IDENT = 2;
  public static final int VOID = 40;
  public static final int FOREACH = 44;
  public static final int LBRACE = 34;
  public static final int ELSE = 28;
  public static final int READ = 39;
  public static final int WHILE = 37;
  public static final int RBRACE = 35;
  public static final int EXTENDS = 46;
  public static final int PROG = 43;
  public static final int LEQ = 19;
  public static final int DEC = 33;
  public static final int GT = 16;
  public static final int DO = 45;
  public static final int PRINT = 38;
}

